name: "\U0001F41B Bug Report"
description: "If something isn't working as expected \U0001F914"
labels: ['needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ## :warning: We use GitHub Issues to track bug reports and feature requests only related to `nest-oidc-provider` module, and not the `oidc-provider` package itself.

        If you are not sure that your issue is a bug, you could [open a discussion](https://github.com/adrianbrs/nest-oidc-provider/discussions/new).
        If your issue is related to the `oidc-provider` package, please visit oidc-provider's [repository](https://github.com/panva/node-oidc-provider). 

        **NOTE:** You don't need to answer questions that you know that aren't relevant.

        ---

  - type: checkboxes
    attributes:
      label: 'Is there an existing issue for this?'
      description: 'Please search [here](../issues?q=is%3Aissue) to see if an issue already exists for the bug you encountered'
      options:
        - label: 'I have searched the existing issues'
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Current behavior'
      description: 'How the issue manifests?'

  - type: input
    validations:
      required: false
    attributes:
      label: 'Minimum reproduction code'
      description: 'An URL to some Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project that reproduces your issue. [Wtf is a minimum reproduction?](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction)'
      placeholder: 'https://github.com/...'

  - type: textarea
    attributes:
      label: 'Steps to reproduce'
      description: |
        How the issue manifests?
        You could leave this blank if you alread write this in your reproduction code
      placeholder: |
        1. `npm ci`
        2. `npm start:dev`
        3. See error...

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Expected behavior'
      description: 'A clear and concise description of what you expected to happend (or code)'

  - type: markdown
    attributes:
      value: |
        ---

  - type: input
    validations:
      required: true
    attributes:
      label: 'oidc-provider version'
      description: |
        Which version of `oidc-provider` are you using?
      placeholder: '7.0.0'

  - type: input
    validations:
      required: true
    attributes:
      label: 'nest-oidc-provider version'
      description: |
        Which version of `nest-oidc-provider` are you using?
      placeholder: '1.1.1'

  - type: input
    attributes:
      label: 'NestJS version'
      description: |
        Which version of `@nestjs/core` are you using?
      placeholder: '8.1.3'

  - type: textarea
    attributes:
      label: 'Packages versions'
      description: |
        You could leave your whole `package.json` dependencies list here
      value: |
        ```json

        ```

  - type: input
    attributes:
      label: 'Node.js version'
      description: 'Which version of Node.js are you using?'
      placeholder: '14.17.6'

  - type: checkboxes
    attributes:
      label: 'In which operating systems have you tested?'
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    attributes:
      label: 'Other'
      description: |
        Anything else relevant? eg: Logs, OS version, IDE, package manager, etc.
        **Tip:** You can attach images, recordings or log files by clicking this area to highlight it and then dragging files in
